version: '3.8' # Specifies the Docker Compose file format version

services:
  backend:
    build:
      context: .
    image: backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      kb_host: "qdrant"
      prompt_path: "prompts/generation.yaml"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      LLM_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 20

  qdrant:
    image: qdrant/qdrant:master
    container_name: qdrant_container
    restart: unless-stopped
    ports:
      - "6333:6333"  # Qdrant default HTTP port
      - "6334:6334"  # Qdrant default gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage  # Persisting data on host
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__LOG_LEVEL: ERROR
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/6333'"]
      interval: 5s
      timeout: 5s
      retries: 10

  tests:
    image: backend:latest
    build:
      context: .
    profiles:
      - test
    env_file: e2e.env
    depends_on:
      backend:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    volumes:
      - ./tests/e2e:/e2e
    environment:
      BACKEND_URL: http://backend:8000
    command: bash -c "uv sync --dev && uv run pytest /e2e -v"
