version: '3.8' # Specifies the Docker Compose file format version

services:
  sim_api:
    build:
      context: .
    image: backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:master
    container_name: qdrant_container
    restart: unless-stopped
    ports:
      - "6333:6333"  # Qdrant default HTTP port
      - "6334:6334"  # Qdrant default gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage  # Persisting data on host
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__LOG_LEVEL: ERROR
